# -*- coding: utf-8 -*-

from odoo import models, fields, api, _
from odoo.exceptions import UserError, ValidationError, Warning

class MedicinaCitaAudiometria(models.Model) :
    _name = 'medicina.cita.audiometria'
    _inherit = 'medicina.cita'
    _description = 'Cita de Audiometría'
    
    audiometria_antecedentes_consumo_tabaco = fields.Boolean(string='''Tabaco (ficha audiológica)''')
    audiometria_antecedentes_hobbies_ruido = fields.Boolean(string='''Hobbies ruidosos (ficha audiológica)''')
    audiometria_antecedentes_infeccion_oido = fields.Boolean(string='''Infecciones de oído previas (ficha audiológica)''')
    audiometria_antecedentes_laboral_quimico = fields.Boolean(string='''Exposición laboral a químicos (ficha audiológica)''')
    audiometria_antecedentes_meningitis_traumatismo = fields.Boolean(string='''Traumatismo encéfalo-craneano o meningitis (ficha audiológica)''')
    audiometria_antecedentes_ototoxicos = fields.Boolean(string='''Uso de ototóxicos (ficha audiológica)''')
    audiometria_antecedentes_servicio_militar = fields.Boolean(string='''Servicio militar (ficha audiológica)''')
    audiometria_antecedentes_trauma_acustico = fields.Boolean(string='''Trauma acústico (ficha audiológica)''')
    audiometria_bilateral = fields.Boolean(string='''Audiometría bilateral''', default=True)
    audiometria_derecho_aerea_1000_nr = fields.Boolean(string='''Audiometría de tipo aérea del oído derecho a 1000 (NR)''')
    audiometria_derecho_aerea_1000_valor = fields.Char(string='''Audiometría de tipo aérea del oído derecho a 1000 (valor)''')
    audiometria_derecho_aerea_125_nr = fields.Boolean(string='''Audiometría de tipo aérea del oído derecho a 125 (NR)''')
    audiometria_derecho_aerea_125_valor = fields.Char(string='''Audiometría de tipo aérea del oído derecho a 125 (valor)''')
    audiometria_derecho_aerea_2000_nr = fields.Boolean(string='''Audiometría de tipo aérea del oído derecho a 2000 (NR)''')
    audiometria_derecho_aerea_2000_valor = fields.Char(string='''Audiometría de tipo aérea del oído derecho a 2000 (valor)''')
    audiometria_derecho_aerea_250_nr = fields.Boolean(string='''Audiometría de tipo aérea del oído derecho a 250 (NR)''')
    audiometria_derecho_aerea_250_valor = fields.Char(string='''Audiometría de tipo aérea del oído derecho a 250 (valor)''')
    audiometria_derecho_aerea_3000_nr = fields.Boolean(string='''Audiometría de tipo aérea del oído derecho a 3000 (NR)''')
    audiometria_derecho_aerea_3000_valor = fields.Char(string='''Audiometría de tipo aérea del oído derecho a 3000 (valor)''')
    audiometria_derecho_aerea_4000_nr = fields.Boolean(string='''Audiometría de tipo aérea del oído derecho a 4000 (NR)''')
    audiometria_derecho_aerea_4000_valor = fields.Char(string='''Audiometría de tipo aérea del oído derecho a 4000 (valor)''')
    audiometria_derecho_aerea_500_nr = fields.Boolean(string='''Audiometría de tipo aérea del oído derecho a 500 (NR)''')
    audiometria_derecho_aerea_500_valor = fields.Char(string='''Audiometría de tipo aérea del oído derecho a 500 (valor)''')
    audiometria_derecho_aerea_6000_nr = fields.Boolean(string='''Audiometría de tipo aérea del oído derecho a 6000 (NR)''')
    audiometria_derecho_aerea_6000_valor = fields.Char(string='''Audiometría de tipo aérea del oído derecho a 6000 (valor)''')
    audiometria_derecho_aerea_8000_nr = fields.Boolean(string='''Audiometría de tipo aérea del oído derecho a 8000 (NR)''')
    audiometria_derecho_aerea_8000_valor = fields.Char(string='''Audiometría de tipo aérea del oído derecho a 8000 (valor)''')
    audiometria_derecho_enmasc_aerea_1000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. aérea. del oído derecho a 1000 (NR)''')
    audiometria_derecho_enmasc_aerea_1000_valor = fields.Char(string='''Audiometría de tipo enmasc. aérea. del oído derecho a 1000 (valor)''')
    audiometria_derecho_enmasc_aerea_125_nr = fields.Boolean(string='''Audiometría de tipo enmasc. aérea. del oído derecho a 125 (NR)''')
    audiometria_derecho_enmasc_aerea_125_valor = fields.Char(string='''Audiometría de tipo enmasc. aérea. del oído derecho a 125 (valor)''')
    audiometria_derecho_enmasc_aerea_2000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. aérea. del oído derecho a 2000 (NR)''')
    audiometria_derecho_enmasc_aerea_2000_valor = fields.Char(string='''Audiometría de tipo enmasc. aérea. del oído derecho a 2000 (valor)''')
    audiometria_derecho_enmasc_aerea_250_nr = fields.Boolean(string='''Audiometría de tipo enmasc. aérea. del oído derecho a 250 (NR)''')
    audiometria_derecho_enmasc_aerea_250_valor = fields.Char(string='''Audiometría de tipo enmasc. aérea. del oído derecho a 250 (valor)''')
    audiometria_derecho_enmasc_aerea_3000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. aérea. del oído derecho a 3000 (NR)''')
    audiometria_derecho_enmasc_aerea_3000_valor = fields.Char(string='''Audiometría de tipo enmasc. aérea. del oído derecho a 3000 (valor)''')
    audiometria_derecho_enmasc_aerea_4000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. aérea. del oído derecho a 4000 (NR)''')
    audiometria_derecho_enmasc_aerea_4000_valor = fields.Char(string='''Audiometría de tipo enmasc. aérea. del oído derecho a 4000 (valor)''')
    audiometria_derecho_enmasc_aerea_500_nr = fields.Boolean(string='''Audiometría de tipo enmasc. aérea. del oído derecho a 500 (NR)''')
    audiometria_derecho_enmasc_aerea_500_valor = fields.Char(string='''Audiometría de tipo enmasc. aérea. del oído derecho a 500 (valor)''')
    audiometria_derecho_enmasc_aerea_6000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. aérea. del oído derecho a 6000 (NR)''')
    audiometria_derecho_enmasc_aerea_6000_valor = fields.Char(string='''Audiometría de tipo enmasc. aérea. del oído derecho a 6000 (valor)''')
    audiometria_derecho_enmasc_aerea_8000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. aérea. del oído derecho a 8000 (NR)''')
    audiometria_derecho_enmasc_aerea_8000_valor = fields.Char(string='''Audiometría de tipo enmasc. aérea. del oído derecho a 8000 (valor)''')
    audiometria_derecho_enmasc_osea_1000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. ósea del oído derecho a 1000 (NR)''')
    audiometria_derecho_enmasc_osea_1000_valor = fields.Char(string='''Audiometría de tipo enmasc. ósea del oído derecho a 1000 (valor)''')
    audiometria_derecho_enmasc_osea_125_nr = fields.Boolean(string='''Audiometría de tipo enmasc. ósea del oído derecho a 125 (NR)''')
    audiometria_derecho_enmasc_osea_125_valor = fields.Char(string='''Audiometría de tipo enmasc. ósea del oído derecho a 125 (valor)''')
    audiometria_derecho_enmasc_osea_2000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. ósea del oído derecho a 2000 (NR)''')
    audiometria_derecho_enmasc_osea_2000_valor = fields.Char(string='''Audiometría de tipo enmasc. ósea del oído derecho a 2000 (valor)''')
    audiometria_derecho_enmasc_osea_250_nr = fields.Boolean(string='''Audiometría de tipo enmasc. ósea del oído derecho a 250 (NR)''')
    audiometria_derecho_enmasc_osea_250_valor = fields.Char(string='''Audiometría de tipo enmasc. ósea del oído derecho a 250 (valor)''')
    audiometria_derecho_enmasc_osea_3000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. ósea del oído derecho a 3000 (NR)''')
    audiometria_derecho_enmasc_osea_3000_valor = fields.Char(string='''Audiometría de tipo enmasc. ósea del oído derecho a 3000 (valor)''')
    audiometria_derecho_enmasc_osea_4000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. ósea del oído derecho a 4000 (NR)''')
    audiometria_derecho_enmasc_osea_4000_valor = fields.Char(string='''Audiometría de tipo enmasc. ósea del oído derecho a 4000 (valor)''')
    audiometria_derecho_enmasc_osea_500_nr = fields.Boolean(string='''Audiometría de tipo enmasc. ósea del oído derecho a 500 (NR)''')
    audiometria_derecho_enmasc_osea_500_valor = fields.Char(string='''Audiometría de tipo enmasc. ósea del oído derecho a 500 (valor)''')
    audiometria_derecho_enmasc_osea_6000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. ósea del oído derecho a 6000 (NR)''')
    audiometria_derecho_enmasc_osea_6000_valor = fields.Char(string='''Audiometría de tipo enmasc. ósea del oído derecho a 6000 (valor)''')
    audiometria_derecho_enmasc_osea_8000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. ósea del oído derecho a 8000 (NR)''')
    audiometria_derecho_enmasc_osea_8000_valor = fields.Char(string='''Audiometría de tipo enmasc. ósea del oído derecho a 8000 (valor)''')
    audiometria_derecho_osea_1000_nr = fields.Boolean(string='''Audiometría de tipo ósea del oído derecho a 1000 (NR)''')
    audiometria_derecho_osea_1000_valor = fields.Char(string='''Audiometría de tipo ósea del oído derecho a 1000 (valor)''')
    audiometria_derecho_osea_125_nr = fields.Boolean(string='''Audiometría de tipo ósea del oído derecho a 125 (NR)''')
    audiometria_derecho_osea_125_valor = fields.Char(string='''Audiometría de tipo ósea del oído derecho a 125 (valor)''')
    audiometria_derecho_osea_2000_nr = fields.Boolean(string='''Audiometría de tipo ósea del oído derecho a 2000 (NR)''')
    audiometria_derecho_osea_2000_valor = fields.Char(string='''Audiometría de tipo ósea del oído derecho a 2000 (valor)''')
    audiometria_derecho_osea_250_nr = fields.Boolean(string='''Audiometría de tipo ósea del oído derecho a 250 (NR)''')
    audiometria_derecho_osea_250_valor = fields.Char(string='''Audiometría de tipo ósea del oído derecho a 250 (valor)''')
    audiometria_derecho_osea_3000_nr = fields.Boolean(string='''Audiometría de tipo ósea del oído derecho a 3000 (NR)''')
    audiometria_derecho_osea_3000_valor = fields.Char(string='''Audiometría de tipo ósea del oído derecho a 3000 (valor)''')
    audiometria_derecho_osea_4000_nr = fields.Boolean(string='''Audiometría de tipo ósea del oído derecho a 4000 (NR)''')
    audiometria_derecho_osea_4000_valor = fields.Char(string='''Audiometría de tipo ósea del oído derecho a 4000 (valor)''')
    audiometria_derecho_osea_500_nr = fields.Boolean(string='''Audiometría de tipo ósea del oído derecho a 500 (NR)''')
    audiometria_derecho_osea_500_valor = fields.Char(string='''Audiometría de tipo ósea del oído derecho a 500 (valor)''')
    audiometria_derecho_osea_6000_nr = fields.Boolean(string='''Audiometría de tipo ósea del oído derecho a 6000 (NR)''')
    audiometria_derecho_osea_6000_valor = fields.Char(string='''Audiometría de tipo ósea del oído derecho a 6000 (valor)''')
    audiometria_derecho_osea_8000_nr = fields.Boolean(string='''Audiometría de tipo ósea del oído derecho a 8000 (NR)''')
    audiometria_derecho_osea_8000_valor = fields.Char(string='''Audiometría de tipo ósea del oído derecho a 8000 (valor)''')
    audiometria_diagnostico = fields.Selection(string='''Diagnóstico (audiometría)''',selection=[("diagnostico_medicina_ocupacional","DiagMO"),("otros_diagnosticos","OtrosD")])
    audiometria_izquierdo_aerea_1000_nr = fields.Boolean(string='''Audiometría de tipo aérea del oído izquierdo a 1000 (NR)''')
    audiometria_izquierdo_aerea_1000_valor = fields.Char(string='''Audiometría de tipo aérea del oído izquierdo a 1000 (valor)''')
    audiometria_izquierdo_aerea_125_nr = fields.Boolean(string='''Audiometría de tipo aérea del oído izquierdo a 125 (NR)''')
    audiometria_izquierdo_aerea_125_valor = fields.Char(string='''Audiometría de tipo aérea del oído izquierdo a 125 (valor)''')
    audiometria_izquierdo_aerea_2000_nr = fields.Boolean(string='''Audiometría de tipo aérea del oído izquierdo a 2000 (NR)''')
    audiometria_izquierdo_aerea_2000_valor = fields.Char(string='''Audiometría de tipo aérea del oído izquierdo a 2000 (valor)''')
    audiometria_izquierdo_aerea_250_nr = fields.Boolean(string='''Audiometría de tipo aérea del oído izquierdo a 250 (NR)''')
    audiometria_izquierdo_aerea_250_valor = fields.Char(string='''Audiometría de tipo aérea del oído izquierdo a 250 (valor)''')
    audiometria_izquierdo_aerea_3000_nr = fields.Boolean(string='''Audiometría de tipo aérea del oído izquierdo a 3000 (NR)''')
    audiometria_izquierdo_aerea_3000_valor = fields.Char(string='''Audiometría de tipo aérea del oído izquierdo a 3000 (valor)''')
    audiometria_izquierdo_aerea_4000_nr = fields.Boolean(string='''Audiometría de tipo aérea del oído izquierdo a 4000 (NR)''')
    audiometria_izquierdo_aerea_4000_valor = fields.Char(string='''Audiometría de tipo aérea del oído izquierdo a 4000 (valor)''')
    audiometria_izquierdo_aerea_500_nr = fields.Boolean(string='''Audiometría de tipo aérea del oído izquierdo a 500 (NR)''')
    audiometria_izquierdo_aerea_500_valor = fields.Char(string='''Audiometría de tipo aérea del oído izquierdo a 500 (valor)''')
    audiometria_izquierdo_aerea_6000_nr = fields.Boolean(string='''Audiometría de tipo aérea del oído izquierdo a 6000 (NR)''')
    audiometria_izquierdo_aerea_6000_valor = fields.Char(string='''Audiometría de tipo aérea del oído izquierdo a 6000 (valor)''')
    audiometria_izquierdo_aerea_8000_nr = fields.Boolean(string='''Audiometría de tipo aérea del oído izquierdo a 8000 (NR)''')
    audiometria_izquierdo_aerea_8000_valor = fields.Char(string='''Audiometría de tipo aérea del oído izquierdo a 8000 (valor)''')
    audiometria_izquierdo_enmasc_aerea_1000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. aérea. del oído izquierdo a 1000 (NR)''')
    audiometria_izquierdo_enmasc_aerea_1000_valor = fields.Char(string='''Audiometría de tipo enmasc. aérea. del oído izquierdo a 1000 (valor)''')
    audiometria_izquierdo_enmasc_aerea_125_nr = fields.Boolean(string='''Audiometría de tipo enmasc. aérea. del oído izquierdo a 125 (NR)''')
    audiometria_izquierdo_enmasc_aerea_125_valor = fields.Char(string='''Audiometría de tipo enmasc. aérea. del oído izquierdo a 125 (valor)''')
    audiometria_izquierdo_enmasc_aerea_2000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. aérea. del oído izquierdo a 2000 (NR)''')
    audiometria_izquierdo_enmasc_aerea_2000_valor = fields.Char(string='''Audiometría de tipo enmasc. aérea. del oído izquierdo a 2000 (valor)''')
    audiometria_izquierdo_enmasc_aerea_250_nr = fields.Boolean(string='''Audiometría de tipo enmasc. aérea. del oído izquierdo a 250 (NR)''')
    audiometria_izquierdo_enmasc_aerea_250_valor = fields.Char(string='''Audiometría de tipo enmasc. aérea. del oído izquierdo a 250 (valor)''')
    audiometria_izquierdo_enmasc_aerea_3000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. aérea. del oído izquierdo a 3000 (NR)''')
    audiometria_izquierdo_enmasc_aerea_3000_valor = fields.Char(string='''Audiometría de tipo enmasc. aérea. del oído izquierdo a 3000 (valor)''')
    audiometria_izquierdo_enmasc_aerea_4000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. aérea. del oído izquierdo a 4000 (NR)''')
    audiometria_izquierdo_enmasc_aerea_4000_valor = fields.Char(string='''Audiometría de tipo enmasc. aérea. del oído izquierdo a 4000 (valor)''')
    audiometria_izquierdo_enmasc_aerea_500_nr = fields.Boolean(string='''Audiometría de tipo enmasc. aérea. del oído izquierdo a 500 (NR)''')
    audiometria_izquierdo_enmasc_aerea_500_valor = fields.Char(string='''Audiometría de tipo enmasc. aérea. del oído izquierdo a 500 (valor)''')
    audiometria_izquierdo_enmasc_aerea_6000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. aérea. del oído izquierdo a 6000 (NR)''')
    audiometria_izquierdo_enmasc_aerea_6000_valor = fields.Char(string='''Audiometría de tipo enmasc. aérea. del oído izquierdo a 6000 (valor)''')
    audiometria_izquierdo_enmasc_aerea_8000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. aérea. del oído izquierdo a 8000 (NR)''')
    audiometria_izquierdo_enmasc_aerea_8000_valor = fields.Char(string='''Audiometría de tipo enmasc. aérea. del oído izquierdo a 8000 (valor)''')
    audiometria_izquierdo_enmasc_osea_1000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. ósea del oído izquierdo a 1000 (NR)''')
    audiometria_izquierdo_enmasc_osea_1000_valor = fields.Char(string='''Audiometría de tipo enmasc. ósea del oído izquierdo a 1000 (valor)''')
    audiometria_izquierdo_enmasc_osea_125_nr = fields.Boolean(string='''Audiometría de tipo enmasc. ósea del oído izquierdo a 125 (NR)''')
    audiometria_izquierdo_enmasc_osea_125_valor = fields.Char(string='''Audiometría de tipo enmasc. ósea del oído izquierdo a 125 (valor)''')
    audiometria_izquierdo_enmasc_osea_2000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. ósea del oído izquierdo a 2000 (NR)''')
    audiometria_izquierdo_enmasc_osea_2000_valor = fields.Char(string='''Audiometría de tipo enmasc. ósea del oído izquierdo a 2000 (valor)''')
    audiometria_izquierdo_enmasc_osea_250_nr = fields.Boolean(string='''Audiometría de tipo enmasc. ósea del oído izquierdo a 250 (NR)''')
    audiometria_izquierdo_enmasc_osea_250_valor = fields.Char(string='''Audiometría de tipo enmasc. ósea del oído izquierdo a 250 (valor)''')
    audiometria_izquierdo_enmasc_osea_3000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. ósea del oído izquierdo a 3000 (NR)''')
    audiometria_izquierdo_enmasc_osea_3000_valor = fields.Char(string='''Audiometría de tipo enmasc. ósea del oído izquierdo a 3000 (valor)''')
    audiometria_izquierdo_enmasc_osea_4000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. ósea del oído izquierdo a 4000 (NR)''')
    audiometria_izquierdo_enmasc_osea_4000_valor = fields.Char(string='''Audiometría de tipo enmasc. ósea del oído izquierdo a 4000 (valor)''')
    audiometria_izquierdo_enmasc_osea_500_nr = fields.Boolean(string='''Audiometría de tipo enmasc. ósea del oído izquierdo a 500 (NR)''')
    audiometria_izquierdo_enmasc_osea_500_valor = fields.Char(string='''Audiometría de tipo enmasc. ósea del oído izquierdo a 500 (valor)''')
    audiometria_izquierdo_enmasc_osea_6000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. ósea del oído izquierdo a 6000 (NR)''')
    audiometria_izquierdo_enmasc_osea_6000_valor = fields.Char(string='''Audiometría de tipo enmasc. ósea del oído izquierdo a 6000 (valor)''')
    audiometria_izquierdo_enmasc_osea_8000_nr = fields.Boolean(string='''Audiometría de tipo enmasc. ósea del oído izquierdo a 8000 (NR)''')
    audiometria_izquierdo_enmasc_osea_8000_valor = fields.Char(string='''Audiometría de tipo enmasc. ósea del oído izquierdo a 8000 (valor)''')
    audiometria_izquierdo_osea_1000_nr = fields.Boolean(string='''Audiometría de tipo ósea del oído izquierdo a 1000 (NR)''')
    audiometria_izquierdo_osea_1000_valor = fields.Char(string='''Audiometría de tipo ósea del oído izquierdo a 1000 (valor)''')
    audiometria_izquierdo_osea_125_nr = fields.Boolean(string='''Audiometría de tipo ósea del oído izquierdo a 125 (NR)''')
    audiometria_izquierdo_osea_125_valor = fields.Char(string='''Audiometría de tipo ósea del oído izquierdo a 125 (valor)''')
    audiometria_izquierdo_osea_2000_nr = fields.Boolean(string='''Audiometría de tipo ósea del oído izquierdo a 2000 (NR)''')
    audiometria_izquierdo_osea_2000_valor = fields.Char(string='''Audiometría de tipo ósea del oído izquierdo a 2000 (valor)''')
    audiometria_izquierdo_osea_250_nr = fields.Boolean(string='''Audiometría de tipo ósea del oído izquierdo a 250 (NR)''')
    audiometria_izquierdo_osea_250_valor = fields.Char(string='''Audiometría de tipo ósea del oído izquierdo a 250 (valor)''')
    audiometria_izquierdo_osea_3000_nr = fields.Boolean(string='''Audiometría de tipo ósea del oído izquierdo a 3000 (NR)''')
    audiometria_izquierdo_osea_3000_valor = fields.Char(string='''Audiometría de tipo ósea del oído izquierdo a 3000 (valor)''')
    audiometria_izquierdo_osea_4000_nr = fields.Boolean(string='''Audiometría de tipo ósea del oído izquierdo a 4000 (NR)''')
    audiometria_izquierdo_osea_4000_valor = fields.Char(string='''Audiometría de tipo ósea del oído izquierdo a 4000 (valor)''')
    audiometria_izquierdo_osea_500_nr = fields.Boolean(string='''Audiometría de tipo ósea del oído izquierdo a 500 (NR)''')
    audiometria_izquierdo_osea_500_valor = fields.Char(string='''Audiometría de tipo ósea del oído izquierdo a 500 (valor)''')
    audiometria_izquierdo_osea_6000_nr = fields.Boolean(string='''Audiometría de tipo ósea del oído izquierdo a 6000 (NR)''')
    audiometria_izquierdo_osea_6000_valor = fields.Char(string='''Audiometría de tipo ósea del oído izquierdo a 6000 (valor)''')
    audiometria_izquierdo_osea_8000_nr = fields.Boolean(string='''Audiometría de tipo ósea del oído izquierdo a 8000 (NR)''')
    audiometria_izquierdo_osea_8000_valor = fields.Char(string='''Audiometría de tipo ósea del oído izquierdo a 8000 (valor)''')
    audiometria_orejeras = fields.Boolean(string='''Orejeras (ficha audiológica)''')
    audiometria_otoscopia_derecho = fields.Char(string='''Otoscopía del oído derecho''')
    audiometria_otoscopia_izquierdo = fields.Char(string='''Otoscopía del oído izquierdo''')
    audiometria_ruido_moderado = fields.Boolean(string='''Ruido moderado''')
    audiometria_ruido_muy_intenso = fields.Boolean(string='''Ruido muy intenso''')
    audiometria_ruido_no_molesto = fields.Boolean(string='''Ruido no molesto''')
    audiometria_sintomas_disminucion_audicion = fields.Boolean(string='''Disminución de la audición (ficha audiológica)''')
    audiometria_sintomas_dolor_oidos = fields.Boolean(string='''Dolor de oídos (ficha audiológica)''')
    audiometria_sintomas_exposicion_ruido_18_horas = fields.Boolean(string='''Exposición a ruidos en las últimas 18 horas (ficha audiológica)''')
    audiometria_sintomas_infeccion_oido = fields.Boolean(string='''Infección de oído (ficha audiológica)''')
    audiometria_sintomas_mareos = fields.Boolean(string='''Mareos (ficha audiológica)''')
    audiometria_sintomas_otros = fields.Char(string='''Otros síntomas (ficha audiológica)''')
    audiometria_sintomas_otros_hay = fields.Boolean(string='''¿Hay otros síntomas? (ficha audiológica)''')
    audiometria_sintomas_zumbidos = fields.Boolean(string='''Zumbidos (ficha audiológica)''')
    audiometria_suma_decibeles_umbral_auditivo_porcentaje = fields.Float(string='''Porcentaje de la suma de decibeles del umbral auditivo''')
    audiometria_suma_decibeles_umbral_auditivo_resultado = fields.Selection(string='''Resultado de la suma de decibeles del umbral auditivo''',selection=[("normal","Normal"),("anormal","Anormal")])
    audiometria_suma_decibeles_umbral_auditivo_valor = fields.Integer(string='''Valor de la suma de decibeles del umbral auditivo''')
    audiometria_tapones = fields.Boolean(string='''Tapones (ficha audiológica)''')
    archivo_adjunto_audiometria_1 = fields.Binary(string='''New Archivo''')
    archivo_adjunto_audiometria_1_filename = fields.Char(string='''Filename for archivo_adjunto_audiometria_1''')
    archivo_adjunto_audiometria_2 = fields.Binary(string='''New Archivo''')
    archivo_adjunto_audiometria_2_filename = fields.Char(string='''Filename for archivo_adjunto_audiometria_2''')
    archivo_adjunto_audiometria_3 = fields.Binary(string='''New Archivo''')
    archivo_adjunto_audiometria_3_filename = fields.Char(string='''Filename for archivo_adjunto_audiometria_3''')
    archivo_adjunto_audiometria_4 = fields.Binary(string='''New Archivo''')
    archivo_adjunto_audiometria_4_filename = fields.Char(string='''Filename for archivo_adjunto_audiometria_4''')
    cie_10_audiometria_codigo_derecho = fields.Char(string='''Código CIE-10 de la audiometría del oído derecho''')
    cie_10_audiometria_codigo_izquierdo = fields.Char(string='''Código CIE-10 de la audiometría del oído izquierdo''')
    cie_10_audiometria_descripcion_bilateral = fields.Char(string='''Descripción CIE-10 de la audiometría bilateral''')
    cie_10_audiometria_descripcion_derecho = fields.Char(string='''Descripción CIE-10 de la audiometría del oído derecho''')
    cie_10_audiometria_descripcion_izquierdo = fields.Char(string='''Descripción CIE-10 de la audiometría del oído izquierdo''')
    cie_10_audiometria_recomendaciones_bilateral = fields.Text(string='''Recomendaciones CIE-10 de la audiometría bilateral''')
    cie_10_audiometria_recomendaciones_derecho = fields.Text(string='''Recomendaciones CIE-10 de la audiometría del oído derecho''')
    cie_10_audiometria_recomendaciones_izquierdo = fields.Text(string='''Recomendaciones CIE-10 de la audiometría del oído izquierdo''')
